### ISSUE TITLE
Algorithmic Final Review Ticket

### ISSUE THREAD

**Issue by Anirudh123nasty** [Athena9355/Tri3-Data-Structure#6]

**Comment by Anirudh123nasty** [comment]
**Quality of work**

- [ ] Share link(s) on slack to final work:  GitHub pages, Replit, Review Ticket(s), TimeBox, or other methods you have used to organize work.

**Coding Review**

- [ ] Individual Coding:

  - [ ] GitHub Pages showing key learnings and challenges conquered from Tech Talks
  
  - [ ] GitHub commits you have made, show GitHub insights into your code commits.
  
  - [ ] Show Code running on Replit as well as IntelliJ
  
  - [ ] Menu review illustrating use of Lists and navigation: show runtime, code organization, code and comments
  
  - [ ] List and Loops: show runtime, code organization, code and comments
  
  - [ ] Class review and understanding: show runtime, code organization, code and comments

- [ ] Show Crossover contribution:  Highlight work you did in crossover project: show their Replit runtime, code commit(s) in their GitHub repo

- [ ] Show anything you have done to enhance what you have learned from Python code

**Video 2 minutes: showing the above, quality suggested as follows**

- [ ] Make sure you cover everything, but create your own order and optimize time

- [ ] Use Voice or Captions.   Try not to wiggle mouse a lot or over scroll.  Make sure you have a clear plan before you start.

- [ ] Perform video in small parts 15-30 seconds and finish a key subject.  Then put the final Video together with Video editing or Youtube playlists.

**Comment by sonakshibhalla** [comment]
Peer Review: Sonakshi Bhalla

Score: 9.75/10


- github pages looks organized and neat with all required material
- commits are thorough and have everything from past weeks
- menu system with organized files and each function running
- lists and loops is running with tester and all of the information
- Factorial and Odd or even functions are implemented in imperative and OOP
- made a guessnumber function and password generator for the crossover team (-0.25, doesn't run on replit)
- video was good and made 2 minutes
